name: Expression and contexts
on: [push, pull_request, issues, workflow_dispatch]
run-name: "Expression and Contexts by @${{ github.actor }}, event: ${{ github.event_name }}"

jobs:
  runs-on-issues-and-prs:
    runs-on: ubuntu-latest
    if: contains(fromjson('["issues","pull_request"]'), github.event_name)
    steps:
      - name: Runs only if issues has a bug label
        if: contains(github.event.issue.labels.*.name,'bug')
        run: echo ${{ join(github.event.issue.labels.*.name, ', ' ) }}

  using-expression-and-contexts:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo ${{ 'This is a string' }}
          echo ${{ 1 }}
          echo ${{ null }}
          echo ${{ true }}
          echo ${{ true && false }}
      - name: Dump contexts
        run: |
            echo '${{ toJson(github) }}'
            echo '${{ toJson(job) }}'
            echo '${{ toJson(secrets) }}'
            echo '${{ toJson(steps) }}'
            echo '${{ toJson(runner) }}'