name: Manually triggered
on:
  workflow_dispatch:
    inputs:
      string:
        description: A string input
        type: string
        required: true
        default: "Nagesh"
      Options:
        description: An Options input
        required: true
        default: "Option 2"
        type: choice
        options:
          - Option 1
          - Option 2
          - Option 3

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF
      - run: |
          echo "String: ${{ inputs.string }}"
          echo "String: ${{ inputs.Options }}"