name: Renew Test
on: 
  workflow_dispatch:
    inputs:
      renew1:
        description: DEV
        required: true
        type: boolean
        default: true

      renew2:
        description: PROD
        required: true
        type: boolean
        default: true

jobs:
  renew-secrets1:
    name: Renew Secrets1
    if: ${{ inputs.renew1 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Renew Secrets
        run: ${{ inputs.renew1 }}

      - name: Renew Secrets
        run: exit 1
    continue-on-error: false
    
  renew-secrets2:
    name: Renew Secrets2
    if: ${{ inputs.renew1 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Renew Secrets
        run: echo ${{ inputs.renew2.description }}
    continue-on-error: false

      

  SlackFailure:
    name: Slack Notifications
    runs-on: ubuntu-latest
    needs:
      - renew-secrets1
      - renew-secrets2
    if: ${{ failure() }}
    steps:
    - name: Slack Notifications
      run: |
          echo "Failed workflow": ${{ github.workflow }}
          echo "Failed Job": ${{ github.job }}
