name: Renew Secrets
on: [workflow_dispatch]

jobs:
  renew-secrets:
    name: Renew Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Renew Secrets
        run: echo "Renew Secrets"

      - name: Run Some build steps
        run: exit 1

  job2:
    runs-on: ubuntu-latest
    needs: [renew-secrets]
    if: ${{ always() && (needs.renew-secrets.result == 'failure' || needs.renew-secrets.result == 'timed_out') }}
    steps:
      - run: Workflow ${{ needs.failing-job.result }}

