name: Reusable Workflow
on:
  workflow_call:
    inputs:
      name:
        description: "Input Description"
        type: string
        default: "Nagesh"
        required: false
    secrets:
      access-token:
        description: "Secret description"
        required: true

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -a

  logs-context-and-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Display Github Context
        run: echo '${{ toJson(github) }}'
      - name: Display name input
        run: echo ${{ inputs.name }}
      - name: Display access-token secrte
        run: echo '${{ secrets.access-token }}'

