name: Status check functions
on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Step 1
        run: sleep 90
      - name: Step 2
        run: exit 1
      - name: Runs on Cancelled
        if: cancelled()
        run: echo "Runs on Cancelled"
      - name: Runs on Failure
        if: failure()
        run: echo "Run on Failure"
      - name: Runs on Success
        if: success()
        run: echo "Run on Success"
      - name: Always run
        if: always()
        run: echo "Always runn'


  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    if: failure()
    steps:
      - run: echo " Job 2"



    